In [2]:
sentence = "My Name is Luv"
L = 4
dim = 8

In [22]:
import torch
torch.set_printoptions(sci_mode=False)

X = torch.randn(L * dim).view(L, -1)
X

tensor([[ 0.7849, -0.8664, -0.5704, -0.4213,  0.1270, -2.2881, -0.7651,  0.2083],
        [ 0.2349, -1.3822, -1.0465,  1.4141, -1.3525,  0.0387, -0.6949, -0.2850],
        [-0.5416, -0.1017,  2.1061, -1.3323, -1.2048,  0.3653, -0.2022,  0.4389],
        [-0.9081, -1.5706,  1.0735,  0.5775,  0.6379,  0.0062, -0.9665,  0.9437]])

In [23]:
Y = X @ X.T
Y

tensor([[ 7.7497,  1.5949, -1.7199,  0.7951],
        [ 1.5949,  7.4556, -2.4157,  1.1909],
        [-1.7199, -2.4157,  8.3329,  1.9864],
        [ 0.7951,  1.1909,  1.9864,  7.0088]])

In [24]:
from torch.nn import functional as F

sft = F.softmax(Y, dim=0)

sft

tensor([[    0.9969,     0.0028,     0.0000,     0.0020],
        [    0.0021,     0.9952,     0.0000,     0.0029],
        [    0.0001,     0.0001,     0.9982,     0.0065],
        [    0.0010,     0.0019,     0.0017,     0.9886]])